version: '3.1'

services:
  web:
    image: odoo:latest
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./odoo-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./config/odoo.conf:/etc/odoo/odoo.conf
    
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - DB_PORT=5432
      - DB_NAME=postgres

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    ports:
      - 0.0.0.0:5432:5432

    volumes:
      - ./postgres-data:/var/lib/postgresql/data