name: CI/CD

on:
  push:
    branches:
      - main

jobs:

  upload_files:
    name: Upload Docker files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install SSH Key
        run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan -t rsa ${{ secrets.SERVER_HOSTNAME }} >> ~/.ssh/known_hosts
     
      - name: Upload Docker files via SFTP
        run: |
            scp -r ./ ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOSTNAME }}:/deploy/docker/odoo/



      - name: Update server with docker compose
        run: |
          ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOSTNAME }} << 'EOF'
            cd /docker/deploy/odoo
            docker compose -f docker-compose.yml down
            docker compose -f docker-compose.yml pull
            docker compose -f docker-compose.yml up -d
          EOF
          

      
