name: CI/CD

on:
  push:
    branches:
      - main

jobs:

  upload_files:
    name: Upload Docker files
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Install SSH Key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -t rsa ${{ secrets.SERVER_HOSTNAME }} >> ~/.ssh/known_hosts
          
      - name: Upload Docker files via SFTP
        env:
          SSHPASS: ${{ secrets.SERVER_PASSWORD }}
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass
          sshpass -e scp -r ./ ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOSTNAME }}:/docker/odoo

      - name: Update server with docker compose
        env:
          SSHPASS: ${{ secrets.SERVER_PASSWORD }}
        run: |
          sshpass -e ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOSTNAME }} << 'EOF'
            cd /docker/deploy/odoo
            docker compose -f docker-compose.yml down
            docker compose -f docker-compose.yml pull
            docker compose -f docker-compose.yml up -d
          EOF
          

      